### ISSUE TITLE
No such file or directory /etc/sysconfig/network in Docker (bitnami/minideb:stretch)

### ISSUE THREAD

**Issue by kivagant-ba** [3ofcoins/chef-cookbook-hostname#68]
Hello.

I'm using the plugin inside a Docker container built `FROM bitnami/minideb:stretch`. I'm getting the following error:

```
  Errno::ENOENT:
       No such file or directory @ rb_sysopen - /etc/sysconfig/network
     # /tmp/d20190103-486-1w7brb0/cookbooks/hostname/recipes/default.rb:72:in `read'
     # /tmp/d20190103-486-1w7brb0/cookbooks/hostname/recipes/default.rb:72:in `block (2 levels) in from_file'
     # ./spec/unit/recipes/base_executor_spec.rb:103:in `block (3 levels) in <top (required)>'
     # ./spec/unit/recipes/base_executor_spec.rb:109:in `block (4 levels) in <top (required)>'
     # ./spec/unit/recipes/base_executor_spec.rb:108:in `each'
     # ./spec/unit/recipes/base_executor_spec.rb:108:in `block (3 levels) in <top (required)>'
```

Any ideas how to get hostname without reading `/etc/sysconfig/network` in Chef?

**Comment by kivagant-ba** [comment]
My workaround in Dockerfile:

```
RUN  mkdir /etc/sysconfig && echo "HOSTNAME=\"$(hostname -f)\"" > /etc/sysconfig/network
```
